// <auto-generated />
using System;
using Medicine.API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Medicine.API.Migrations
{
    [DbContext(typeof(ApiContext))]
    [Migration("20210124060759_Change_Models_Add_SpecialtyController")]
    partial class Change_Models_Add_SpecialtyController
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("Medicine.API.Models.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("EmployeerId")
                        .HasColumnType("int");

                    b.Property<int?>("PhysicianId")
                        .HasColumnType("int");

                    b.Property<string>("Qualification")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeerId");

                    b.HasIndex("PhysicianId");

                    b.ToTable("Doctors");
                });

            modelBuilder.Entity("Medicine.API.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("DayOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Patronymic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Medicine.API.Models.Specialty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Specialties");
                });

            modelBuilder.Entity("Medicine.API.Models.Doctor", b =>
                {
                    b.HasOne("Medicine.API.Models.Employee", "Employeer")
                        .WithMany("Doctors")
                        .HasForeignKey("EmployeerId");

                    b.HasOne("Medicine.API.Models.Specialty", "Physician")
                        .WithMany("Doctors")
                        .HasForeignKey("PhysicianId");

                    b.Navigation("Employeer");

                    b.Navigation("Physician");
                });

            modelBuilder.Entity("Medicine.API.Models.Employee", b =>
                {
                    b.Navigation("Doctors");
                });

            modelBuilder.Entity("Medicine.API.Models.Specialty", b =>
                {
                    b.Navigation("Doctors");
                });
#pragma warning restore 612, 618
        }
    }
}
